### PR TITLE
Fixing Authorize button

### PR DESCRIPTION
**Pull request by yagoodman**
href pointing to a non-existing path

### CODE REVIEW

**Comment by MisinformedDNA** [comment]
I just ran into this today. Can we get this merged?

**Comment by MisinformedDNA** [comment]
Fixes #36

**Comment by millanie** [comment]
Authorize button does not work. Can you update the progress?

**Comment by millanie** [comment]
@jynxeh The change also doesn't work. When it redirect to auth/authorize, it returns 400 bad request error.

**Comment by jynxeh** [comment]
@millanie if you're seeing a 400 from VSTS I would guess you haven't updated the web config with your app registration details. You need to replace the values in this section:

    
    <add key="ClientAppId" value="{insert client app ID here}"/>
    <add key="ClientAppSecret" value="{insert client secret here}"/>
    <add key="Scope" value="{insert space-separated scope list here}"/>
    <add key="CallbackUrl" value="{ insert redirect/callback URL here}"/>

**Comment by millanie** [comment]
@jynxeh I think that you need to add approving review for merge. 
Anyway, I checked that it worked with the correct information with callback url. 
Thanks!

**Comment by jynxeh** [comment]
@JimsonChalissery can you approve this? It's a very simple fix which at the moment has been breaking this sample entirely for over a year. Many thanks.

**Comment by anydot** [comment]
Will be fixed in PR #59

**Pull request closed without merging**
